use std::{env, fs, path::PathBuf};

use anyhow::{Context, Result, bail};

use crate::config::{Config, state_root};

#[cfg(windows)]
const WINDOWS_MARKER: &str = ":: Generated by routeai.\r\n";

pub fn directory() -> Result<PathBuf> {
    let fallback = state_root()?.join("bin");
    if ["claude", "codex"]
        .iter()
        .map(|name| shim_path(&fallback, name))
        .any(|path| path.symlink_metadata().is_ok())
    {
        return Ok(fallback);
    }
    let executable = env::current_exe()?.canonicalize()?;
    if let Some(directory) = executable_on_path(&executable)
        && shim_paths_available(&directory, &executable)
    {
        return Ok(directory);
    }
    Ok(fallback)
}

pub fn on_path(directory: &std::path::Path) -> bool {
    env::var_os("PATH").is_some_and(|paths| {
        env::split_paths(&paths).any(|entry| {
            entry == directory || entry.canonicalize().is_ok_and(|entry| entry == directory)
        })
    })
}

pub fn install(config: &Config) -> Result<PathBuf> {
    let mut directory = directory()?;
    if on_path(&directory) && !precedes_provider_commands(&directory, config) {
        directory = state_root()?.join("bin");
    }
    fs::create_dir_all(&directory)?;
    let executable = env::current_exe()?.canonicalize()?;
    for name in ["claude", "codex"] {
        let path = shim_path(&directory, name);
        if path.symlink_metadata().is_ok() {
            if owned_by_routeai(&path, Some(&executable)) {
                #[cfg(windows)]
                create_shim(&executable, &path, name)
                    .with_context(|| format!("could not update {}", path.display()))?;
                continue;
            }
            bail!("refusing to replace {}", path.display());
        }
        create_shim(&executable, &path, name)
            .with_context(|| format!("could not create {}", path.display()))?;
    }
    Ok(directory)
}

pub fn precedes_provider_commands(directory: &std::path::Path, config: &Config) -> bool {
    let Some(shim_position) = path_position(directory) else {
        return false;
    };
    [
        config.providers.claude.command.as_deref(),
        config.providers.codex.command.as_deref(),
    ]
    .into_iter()
    .flatten()
    .filter_map(std::path::Path::parent)
    .all(|provider_directory| {
        path_position(provider_directory).is_none_or(|position| shim_position < position)
    })
}

pub fn uninstall() -> Result<PathBuf> {
    let directory = directory()?;
    let executable = env::current_exe()?.canonicalize()?;
    for name in ["claude", "codex"] {
        let path = shim_path(&directory, name);
        if path.symlink_metadata().is_err() {
            continue;
        }
        if !owned_by_routeai(&path, Some(&executable)) {
            bail!(
                "refusing to remove {} because routeai does not own it",
                path.display()
            );
        }
        fs::remove_file(path)?;
    }
    Ok(directory)
}

pub fn installed() -> Result<bool> {
    let directory = directory()?;
    let executable = env::current_exe()?.canonicalize()?;
    Ok(["claude", "codex"]
        .iter()
        .map(|name| shim_path(&directory, name))
        .all(|path| owned_by_routeai(&path, Some(&executable))))
}

pub fn is_managed(path: &std::path::Path, executable: Option<&std::path::Path>) -> bool {
    owned_by_routeai(path, executable)
}

fn shim_path(directory: &std::path::Path, name: &str) -> PathBuf {
    if cfg!(windows) {
        directory.join(format!("{name}.cmd"))
    } else {
        directory.join(name)
    }
}

fn executable_on_path(executable: &std::path::Path) -> Option<PathBuf> {
    let paths = env::var_os("PATH")?;
    let name = if cfg!(windows) {
        "routeai.exe"
    } else {
        "routeai"
    };
    env::split_paths(&paths).find_map(|directory| {
        let candidate = directory.join(name);
        (candidate.canonicalize().ok().as_deref() == Some(executable))
            .then(|| directory.canonicalize().unwrap_or(directory))
    })
}

fn path_position(directory: &std::path::Path) -> Option<usize> {
    let paths = env::var_os("PATH")?;
    env::split_paths(&paths).position(|entry| {
        entry == directory || entry.canonicalize().is_ok_and(|entry| entry == directory)
    })
}

fn shim_paths_available(directory: &std::path::Path, executable: &std::path::Path) -> bool {
    ["claude", "codex"].iter().all(|name| {
        let path = shim_path(directory, name);
        path.symlink_metadata().is_err() || owned_by_routeai(&path, Some(executable))
    })
}

#[cfg(unix)]
fn create_shim(target: &std::path::Path, link: &std::path::Path, _: &str) -> std::io::Result<()> {
    std::os::unix::fs::symlink(target, link)
}

#[cfg(windows)]
fn create_shim(
    target: &std::path::Path,
    link: &std::path::Path,
    provider: &str,
) -> std::io::Result<()> {
    let content = format!(
        "{WINDOWS_MARKER}@echo off\r\n\"{}\" __run {provider} %*\r\n",
        target.display()
    );
    fs::write(link, content)
}

#[cfg(unix)]
fn owned_by_routeai(path: &std::path::Path, executable: Option<&std::path::Path>) -> bool {
    executable.is_some_and(|executable| path.canonicalize().ok().as_deref() == Some(executable))
}

#[cfg(windows)]
fn owned_by_routeai(path: &std::path::Path, _: Option<&std::path::Path>) -> bool {
    fs::read_to_string(path).is_ok_and(|content| content.starts_with(WINDOWS_MARKER))
}
