use std::{env, fs, path::PathBuf};

use anyhow::{Context, Result, bail};

use crate::config::state_root;

#[cfg(windows)]
const WINDOWS_MARKER: &str = ":: Generated by routeai.\r\n";

pub fn directory() -> Result<PathBuf> {
    Ok(state_root()?.join("bin"))
}

pub fn install() -> Result<PathBuf> {
    let directory = directory()?;
    fs::create_dir_all(&directory)?;
    let executable = env::current_exe()?.canonicalize()?;
    for name in ["claude", "codex"] {
        let path = shim_path(&directory, name);
        if path.symlink_metadata().is_ok() {
            if owned_by_routeai(&path, Some(&executable)) {
                #[cfg(windows)]
                create_shim(&executable, &path, name)
                    .with_context(|| format!("could not update {}", path.display()))?;
                continue;
            }
            bail!("refusing to replace {}", path.display());
        }
        create_shim(&executable, &path, name)
            .with_context(|| format!("could not create {}", path.display()))?;
    }
    Ok(directory)
}

pub fn uninstall() -> Result<PathBuf> {
    let directory = directory()?;
    let executable = env::current_exe()?.canonicalize()?;
    for name in ["claude", "codex"] {
        let path = shim_path(&directory, name);
        if path.symlink_metadata().is_err() {
            continue;
        }
        if !owned_by_routeai(&path, Some(&executable)) {
            bail!(
                "refusing to remove {} because routeai does not own it",
                path.display()
            );
        }
        fs::remove_file(path)?;
    }
    Ok(directory)
}

pub fn installed() -> Result<bool> {
    let directory = directory()?;
    let executable = env::current_exe()?.canonicalize()?;
    Ok(["claude", "codex"]
        .iter()
        .map(|name| shim_path(&directory, name))
        .all(|path| owned_by_routeai(&path, Some(&executable))))
}

pub fn is_managed(path: &std::path::Path, executable: Option<&std::path::Path>) -> bool {
    owned_by_routeai(path, executable)
}

fn shim_path(directory: &std::path::Path, name: &str) -> PathBuf {
    if cfg!(windows) {
        directory.join(format!("{name}.cmd"))
    } else {
        directory.join(name)
    }
}

#[cfg(unix)]
fn create_shim(target: &std::path::Path, link: &std::path::Path, _: &str) -> std::io::Result<()> {
    std::os::unix::fs::symlink(target, link)
}

#[cfg(windows)]
fn create_shim(
    target: &std::path::Path,
    link: &std::path::Path,
    provider: &str,
) -> std::io::Result<()> {
    let content = format!(
        "{WINDOWS_MARKER}@echo off\r\n\"{}\" run {provider} -- %*\r\n",
        target.display()
    );
    fs::write(link, content)
}

#[cfg(unix)]
fn owned_by_routeai(path: &std::path::Path, executable: Option<&std::path::Path>) -> bool {
    executable.is_some_and(|executable| path.canonicalize().ok().as_deref() == Some(executable))
}

#[cfg(windows)]
fn owned_by_routeai(path: &std::path::Path, _: Option<&std::path::Path>) -> bool {
    fs::read_to_string(path).is_ok_and(|content| content.starts_with(WINDOWS_MARKER))
}
